CREATE TABLE actor_movie(
    ID INTEGER NOT NULL PRIMARY KEY auto_increment,
    MOVIEID INTEGER NOT NULL,
    ACTORID INTEGER NOT NULL,
    FOREIGN KEY (MOVIEID) REFERENCES movie(ID),
    FOREIGN KEY (ACTORID) REFERENCES actor(ID)
)